### ISSUE TITLE
Error adding company on clean iomad install

### ISSUE THREAD

**Issue by DBezemer** [iomad/iomad#1]
After adding a first company to Iomad, with a logo the dashboard doesnt load anymore and throws the following error:

```
( ! ) Warning: require_once(/opt/moodle/iomad/local/perficio/lib/company.php): failed to open stream: No such file or directory in /opt/moodle/iomad/blocks/iomad_approve_access/lib.php on line 32
```

I think line 32 and 33 of the aforementioned file should read:

```
    require_once($CFG->dirroot.'/local/iomad/lib/company.php');
    require_once($CFG->dirroot.'/local/iomad/lib/user.php');
```

**Comment by DBezemer** [comment]
Or alternatively you forgot to include the perficio libraries as this modification throws another error:

```
Fatal error: Call to undefined method company::get_my_users_list() in /opt/moodle/iomad/blocks/iomad_approve_access/lib.php on line 61
```

**Comment by turf212** [comment]
Firstly, thanks for looking and letting us know!

Its the second issue.  The original system was called Perficio and an update has pulled in the old lib names.  I've fixed and pushed the changes.

**Comment by DBezemer** [comment]
This does not solve the second problem where the method get_my_users_list() is missing from the company.php lib file

**Comment by turf212** [comment]
Updated and pushed. :)

Thanks

**Comment by turf212** [comment]
Heard nothing back.  Closing as resolved.

**Comment by DBezemer** [comment]
It's resolved, so thanks for the quick response
