### ISSUE TITLE
"Error writing to database" assigning department users (educators enabled)

### ISSUE THREAD

**Issue by 2w3nn3r** [iomad/iomad#1584]
Since I have enabled "Course educators" I am no longer able to assign users to departments. Just facing the following error instead. Only Course educator assignment is working. Cannot assign other roles as well. Tested with 3.9.
I enabled debug-mode to see error details: 

```
Error writing to database

More information about this error

Debug info: Column 'educator' cannot be null
INSERT INTO mdl_company_users (companyid,userid,departmentid,educator,managertype) VALUES(?,?,?,?,?)
[array (
0 => 1,
1 => '3',
2 => 7,
3 => NULL,
4 => 0,
)]
Error code: dmlwriteexception

Stack trace:
line 489 of /lib/dml/moodle_database.php: dml_write_exception thrown
line 1357 of /lib/dml/mysqli_native_moodle_database.php: call to moodle_database->query_end()
line 1403 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->insert_record_raw()
line 1018 of /local/iomad/lib/company.php: call to mysqli_native_moodle_database->insert_record()
line 176 of /blocks/iomad_company_admin/classes/forms/company_managers_form.php: call to company::upsert_company_user()
line 136 of /blocks/iomad_company_admin/company_managers_form.php: call to block_iomad_company_admin\forms\company_managers_form->process()

Output buffer: Notice: Trying to get property 'educator' of non-object in .../blocks/iomad_company_admin/classes/forms/company_managers_form.php on line 167

**Comment by turf212** [comment]
The function being called here (upsert_company_user) has had a bit of a rework over the last few weeks.  Can you please pull the latest 3.9 code and check to see if this is now fixed?  the $educator value is being set as false by default so there shouldn't be an empty value in the insert array.

**Comment by 2w3nn3r** [comment]
The problem persists, Tested with latest 3.9_STABLE on two different systems. But I think could identify the code problem in company_managers_form.php (line 164): 

```
 if (!$CFG->iomad_autoenrol_managers && $roletype != 3) {
                        // We have to be mindful of educator types here.
                        $userrec = $DB->get_record('company_users', array('userid' => $adduser->id, 'companyid' => $this->selectedcompany, 'departmentid' => $departmentid));
                        $educator = $userrec->educator;
```
 
The problem is: $userrec is not an object, because $DB->get_record doesn't return a result. So I tested the conditions and found that the $departmentid is not the correct one from the record entry in the database. My database has a record with a departmentid that is "1" but the value stored in $departmentid is "2". So the record cannot be found. If I change the value directly to "1" the error disappears. 
So it's actually a problem that is related to $departmentid, I suppose.

**Comment by turf212** [comment]
Ah, yeah I can see why that would happen.  Need to check if this has a value and only change it if it's already there.

**Comment by francoisjacquet** [comment]
Hello @turf212 

I have the same error after upgrading to IOMAD 3.6.10.
When calling the `block_iomad_company_admin_assign_users` **webservice** function, there is this error showing up:
> Moodle: 84677281 - Error writing to database | DEBUG INFO: ERROR: null value in column "educator" violates not-null constraint DETAIL: Failing row contains (44, 1, 49, 0, 1, 0, null). INSERT INTO mdl_company_users (companyid,userid,departmentid,educator,managertype) VALUES($1,$2,$3,$4,$5) RETURNING id [array ( 'companyid' => 1, 'userid' => 49, 'departmentid' => '1', 'educator' => NULL, 'managertype' => 0, )] | ERRORCODE: dmlwriteexception

I believe the NULL value for educator is here (my guess): https://github.com/iomad/iomad/blob/IOMAD_310_STABLE/blocks/iomad_company_admin/externallib.php#L740

**Comment by hamza452233** [comment]
my issue is about DML exception when I add a student or teacher and try to integrate with my iomad

**Comment by turf212** [comment]
The usertypes was causing no end of issues.  Fixed in 4.1 on.
