### ISSUE TITLE
Assign users to course - shows "too many users..." when there aren't that many users in company

### ISSUE THREAD

**Issue by davidpesce** [iomad/iomad#1647]
IOMAD v3.10.7 (Build: 20210913) - latest as of today
PHP v7.3.31
Apache 2

Navigating to Courses > User enrolments > (select a course) shows more users enrolled (and to enroll) than exist in the company.

Oddly it's also showing more users than even exist in the system.

**Comment by turf212** [comment]
This was an issue due to users being in multiple departments.  It was fixed in d73ddb6a7922281d91e51944fc4b65eff01b5161

**Comment by dcraven002** [comment]
@turf212 this issue is still persisting for us on iomad version 4.4.4, any advice?

I changed the Maximum users per page to 5000 but it didn't solve the issue unfortunately.

<img width="893" alt="Screenshot 2024-12-11 at 11 21 08" src="https://github.com/user-attachments/assets/95b9553d-3d29-4f2a-94a7-976bc741f4c7" />

![Screenshot 2024-12-10 at 13 50 34](https://github.com/user-attachments/assets/b161273d-2b55-458e-9d66-5b7970d1bab1)

<img width="1046" alt="Screenshot 2024-12-11 at 11 19 56" src="https://github.com/user-attachments/assets/834b3282-d9b4-46d8-8860-56b32940b743" />

**Comment by dcraven002** [comment]
Hi @collach would you know if there is any known fix for this bug ? :)

**Comment by collach** [comment]
You should be able to resolve this by increasing iomad_max_select_users under the local IOMAD plugin settings (Site administration -> Plugins -> Local plugins -> IOMAD settings -> Maximum listed users in selector), as this is the value IOMAD uses for the Assign to Course selectors rather than the one set in core Site Admin settings. Let me know if this doesn't fix things and we can look into it.

**Comment by dcraven002** [comment]
@collach  THANK YOU! That worked! Thanks soo much :D
