### ISSUE TITLE
Database errors when filtering reports.

### ISSUE THREAD

**Issue by encodecreate** [iomad/iomad#1723]
Some reports return database errors when attempt to sort or filter by columns containing dates. Instead of filtering or sorting, the report screen shows only an orange error message that says "error reading from database." These errors also occur when tested on the live demo.

Errors:

* User report: cannot sort by "last acccess." If you have attempted to sort by "last access", then "user created" will also break.
* License allocation report: cannot filter by dates (UI is frequently unresponsive).

**Comment by turf212** [comment]
This was fixed in commit a5adf845f5df70899aa694e3ba651573c47de504 on the 14th of Sep.  If you can pull the latest version of the code and confirm please?

**Comment by encodecreate** [comment]
Just pulled the latest code and tried again. Users report and License allocation report are both still broken.

**Comment by dallenk** [comment]
I can confirm this has returned for me as well.  I do believe it was cleared up at one point.

```
Debug info: Column 'lastlogin' in order clause is ambiguous
SELECT
DISTINCT u.*,u.timecreated as created, u.currentlogin as lastlogin, cu.companyid
FROM mdl_user u JOIN mdl_company_users cu ON (u.id = cu.userid) JOIN mdl_department d ON (cu.departmentid = d.id)
WHERE u.id != '-1' and u.deleted = 0 AND u.id NOT IN (2) AND u.suspended = 0 AND cu.companyid = ? AND d.id IN (1)
ORDER BY lastlogin ASC LIMIT 0, 30
[array (
0 => '1',
)]
Error code: dmlreadexception×Dismiss this notification
Stack trace:
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 291 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
line 1273 of /lib/dml/mysqli_native_moodle_database.php: call to mysqli_native_moodle_database->query_end()
line 2110 of /lib/tablelib.php: call to mysqli_native_moodle_database->get_records_sql()
line 2132 of /lib/tablelib.php: call to table_sql->query_db()
line 325 of /local/report_users/index.php: call to table_sql->out()
```

**Comment by turf212** [comment]
Not sure this was ever picked up / fixed when the other reports were done.

**Comment by encodecreate** [comment]
Thanks @turf212 -- that fixed the Users Report.

Unfortunately, the license allocation report is still broken.  I think it might be a JavaScript issue -- the UI to filter is completely unusable.

**Comment by turf212** [comment]
Which license allocation one?  The license allocation report isn't a table and the date columns on the User license allocation report arent sortable.

**Comment by encodecreate** [comment]
Sorry, filtering, not sorting, and on the "License allocation report".

Two separate errors, one related to database, one related to filtering UI.

**Database**
Attempting to filter by "start date" returns a database error. Filtering by "end date" functions as expected.

**UI**
Doing more testing, some companies have different UI errors than others.


Example 1 -- Cannot use filtering UI, checkboxes covering each other in the wrong place, cannot be clicked.
![image](https://user-images.githubusercontent.com/110412239/194375128-9fc42188-fa70-475e-ba6f-7ea934d93d9e.png)


Example 2 -- UI partially non-functional. Cannot select "start date" check box. "end date" check box works, user can filter by end date.
![image](https://user-images.githubusercontent.com/110412239/194375546-f320abaa-18ed-413d-b641-fa97f37d86a4.png)


Example 3 -- UI partially non-functional. Can select "start date", but "end date" check box does not work.  
![image](https://user-images.githubusercontent.com/110412239/194376439-d3de895f-7b01-43b3-a025-339cdb042458.png)


I'm not sure why different companies load differently. Testing on Firefox and Chrome, Windows 10.

I've discovered that for companies where the UI loads improperly, resizing the screen towards mobile width will reload the filtering UI and the check boxes will work as expected. Resizing back to desktop width breaks functionality again.

These UI bugs are consistent across companies. The same companies will load the UI with the same probably, and switching companies will consistently create different UI bugs associated with that company. This can always be fixed by resizing down to mobile width.

**Comment by turf212** [comment]
It's a CSS styling issue.  I've updated how it shows on the report index page.

**Comment by encodecreate** [comment]
That fixed the UI issues, still a database error when attempting to filter using a start date. 

![image](https://user-images.githubusercontent.com/110412239/194566233-1e94de6b-8999-4dfc-b4b9-73979fa110ed.png)

**Comment by turf212** [comment]
duplicate of #1839 - cannot replicate in current code.
