### ISSUE TITLE
Bug in User bulk download :

### ISSUE THREAD

**Issue by Kabilanparadiso** [iomad/iomad#175]
When logged in as a Super-admin, if I download using "User bulk download" for any company, the report is downloaded correctly. But we I change another company using "Select a company" option and  download the report, I am still getting the report of the first company.

In another words, regardless of whatever company reports you are downloading, you always get the report of the first company you downloaded in that particular log in. If I want to download the report of another company, I have to log out and re-login and select that particular company.

**Comment by turf212** [comment]
The tool uses the company you have currently got selected in the dashboard rather than in the page for the user download.  This dropdown needs to be removed.

**Comment by Kabilanparadiso** [comment]
Hi. Thanks for the reply.

I still have the same problem. Let me explain what exactly I done, so that you can help me. I have 2 sample companies. Company A and Company B.

I selected the 'Company A' using the dashboard.The steps are:  IOMAD Dashboad -> Select company (Company A from the dropdown) -> User management -> User bulk download

Using the above steps, i download the .CSV files of Company A. Everything was fine until this point.

Then I wanted to download the report of 'Company B'. So I went back Multi-tenancy dashboard and selected company B.  I followed this steps : IOMAD Dashboad -> Select company (Company B from the dropdown) -> User management -> User bulk download. 

But, instead of report of Company B, once again report of Company A is being downloaded. Then whatever company I am selecting from the dashboard (company C, Company D etc.,) still the same report belonged to the Company A (The first company I selected to download the report in this particular login) is being downloaded. 

Only when I completely logged out and then login and selected company B, the company B report is downloaded. I believed I explained the issue little better.

Thanks in advance.
Regards
Kabi

**Comment by BananaRama203** [comment]
Just to confirm we have the same issue.

**Comment by turf212** [comment]
This is likely due to the fact that you have assigned your own user to a company.  There is a snippet of code in the bulk download which reads -

// If company user override the companyid parameter - they can only download their own.
if (company_user::is_company_user()) {
    $companyid = company_user::companyid();
}

Its fairly redundant as the company id is properly set further up.

**Comment by BananaRama203** [comment]
Just to confirm that the SA account doesn't exist in mdl_company_users and isn't assigned to a company and the issue still persists.

**Comment by turf212** [comment]
fixed in 2.7 and 2.8

**Comment by BananaRama203** [comment]
Apologies I am still having the same issue and I have updated to latest commits. You can log in our system to confirm issue still exists.
