### ISSUE TITLE
Site fail after last updates

### ISSUE THREAD

**Issue by dallenk** [iomad/iomad#1762]
After the latest updates to code no users other than the Site Administrator are able to see the "My Courses" or "Dashboard" pages.

This is affecting all users on production and dev site, cache was cleared and the problem still remains.   Trying a rollback to previous commit on the dev site

@turf212

**Comment by dallenk** [comment]
Debug info:
Error code: unknowncategory
Stack trace:
line 267 of /course/classes/category.php: moodle_exception thrown
line 68 of /course/classes/external/course_summary_exporter.php: call to core_course_category::get()
line 125 of /lib/classes/external/exporter.php: call to core_course\external\course_summary_exporter->get_other_values()
line 102 of /blocks/mycourses/classes/output/available_view.php: call to core\external\exporter->export()
line 93 of /blocks/mycourses/classes/output/main.php: call to block_mycourses\output\available_view->export_for_template()
line 46 of /blocks/mycourses/classes/output/renderer.php: call to block_mycourses\output\main->export_for_template()
line 533 of /lib/outputrenderers.php: call to block_mycourses\output\renderer->render_main()
line 57 of /blocks/mycourses/block_mycourses.php: call to plugin_renderer_base->render()
line 341 of /blocks/moodleblock.class.php: call to block_mycourses->get_content()
line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
line 1222 of /lib/blocklib.php: call to block_base->get_content_for_output()
line 1280 of /lib/blocklib.php: call to block_manager->create_block_contents()
line 730 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
line 285 of /theme/iomadboost/classes/output/core_renderer.php: call to core_renderer->standard_head_html()
line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_iomadboost\output\core_renderer->standard_head_html()
line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
line 31 of /var/www/vhosts/[domain.ca/moodledata/localcache/mustache/1675367451/iomadboost/__Mustache_eb4b45ecbe4f60a84b8a56326203be46.php](http://domain.ca/moodledata/localcache/mustache/1675367451/iomadboost/__Mustache_eb4b45ecbe4f60a84b8a56326203be46.php): call to Mustache_Context->findDot()
line 13 of /var/www/vhosts/[domain.ca/moodledata/localcache/mustache/1675367451/iomadboost/__Mustache_378182edff0932b3ddd4d9c9caea7dfd.php](http://domain.ca/moodledata/localcache/mustache/1675367451/iomadboost/__Mustache_378182edff0932b3ddd4d9c9caea7dfd.php): call to __Mustache_eb4b45ecbe4f60a84b8a56326203be46->renderInternal()
line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_378182edff0932b3ddd4d9c9caea7dfd->renderInternal()
line 204 of /lib/outputrenderers.php: call to Mustache_Template->render()
line 113 of /theme/iomadboost/layout/drawers.php: call to renderer_base->render_from_template()
line 1515 of /lib/outputrenderers.php: call to include()
line 1441 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
line 179 of /my/index.php: call to core_renderer->header()

**Comment by dallenk** [comment]
resetting to commit a2702e7651d did not resolve the error.  I ended up restoring a nightly backup of  the database, iomad/ and moodledata/ to restore the site.

I will make a live copy of the current commit level(backup taken 14 hours ago)

git log --oneline
6c178769a76 (HEAD -> IOMAD_400_STABLE_2, origin/IOMAD_400_STABLE) IOMAD: 4.0.6 release
d103540c493 Merge branch 'MOODLE_400_STABLE' of git://git.moodle.org/moodle into IOMAD_400_STABLE



I will try to replicate it with incremental updates one commit at a time.

**Comment by turf212** [comment]
There was a hotfix pushed yesterday for this on 4.0 under commit d0ef84f7b46bfa696ff977df2c2ca5d814836549  The previous security fix to stop users from accessing course categories directly on the URL that they shouldn't see broke it.

**Comment by dallenk** [comment]
Thanks, but the issue remained after applying commit d0ef84f.  I tried clearing all cache on server and browser and the category error was still showing.

is it possible that during the time between 9b02e41 (with a database upgrade) then the commit for d0ef84f for the fix caused something the database to be written/read incorrectly for the fixed code?

**Comment by dallenk** [comment]
Doing some more troubleshooting on the dev site.. very basic setup with 4 companies and a few users
Updated to the most current commit:
```
me@domain:/var/www/vhosts/001-dev.domain.ca/iomad$ git log --oneline
d0ef84f7b46 (HEAD -> IOMAD_400_STABLE, origin/IOMAD_400_STABLE) IOMAD: course catalog change caused an issue with the new 'courses' page
```
As the Administrator I can log into the main/root URL (dev.domain.ca)  without issue and navigate wherever I need.  "My Courses / Dashboard / Site Admin / Company Dashboard" all function fine.

### As a user of a company c1.dev.domain.ca or c2.dev.domain.ca I see this immediately after login (likely due to the start page for users set to: Dashboard)
![image](https://user-images.githubusercontent.com/2725066/216796295-8bec6c24-126a-47a0-921e-051a2a0c713f.png)

### If I edit the url to:  c1.dev.domain.ca/?redirect=0  I can access "home" of each company (only odd numbered are shared with C1, even with C2 so I know the correct categories are being displayed)
![image](https://user-images.githubusercontent.com/2725066/216797008-1f20fe3e-f3ff-4616-a4b8-9ee357bdbbc7.png)

### user of c2.dev.domain.ca sees the same upon login, and changing the url to ?redirect=0 shows the even numbered courses..
![image](https://user-images.githubusercontent.com/2725066/216797077-8ac9eaae-c84a-48e4-8358-511ad7925baa.png)


### enabling debug shows the following error when accessing "Dashboard" or "My Courses", but only on companies other than the main.
C1 and C2 do not have parent companies (set to none, not sure if this matters, but I know companies are just categories anyway)

```
Error
Unknown category
Debug info:
Error code: unknowncategory
Stack trace:

    line 267 of /course/classes/category.php: moodle_exception thrown
    line 68 of /course/classes/external/course_summary_exporter.php: call to core_course_category::get()
    line 125 of /lib/classes/external/exporter.php: call to core_course\external\course_summary_exporter->get_other_values()
    line 102 of /blocks/mycourses/classes/output/available_view.php: call to core\external\exporter->export()
    line 93 of /blocks/mycourses/classes/output/main.php: call to block_mycourses\output\available_view->export_for_template()
    line 46 of /blocks/mycourses/classes/output/renderer.php: call to block_mycourses\output\main->export_for_template()
    line 533 of /lib/outputrenderers.php: call to block_mycourses\output\renderer->render_main()
    line 57 of /blocks/mycourses/block_mycourses.php: call to plugin_renderer_base->render()
    line 341 of /blocks/moodleblock.class.php: call to block_mycourses->get_content()
    line 235 of /blocks/moodleblock.class.php: call to block_base->formatted_contents()
    line 1222 of /lib/blocklib.php: call to block_base->get_content_for_output()
    line 1280 of /lib/blocklib.php: call to block_manager->create_block_contents()
    line 730 of /lib/outputrenderers.php: call to block_manager->ensure_content_created()
    line 285 of /theme/iomadboost/classes/output/core_renderer.php: call to core_renderer->standard_head_html()
    line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_iomadboost\output\core_renderer->standard_head_html()
    line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
    line 31 of /var/www/vhosts/001-dev.domain.ca/moodledata/localcache/mustache/1675549525/iomadboost/__Mustache_eb4b45ecbe4f60a84b8a56326203be46.php: call to Mustache_Context->findDot()
    line 13 of /var/www/vhosts/001-dev.domain.ca/moodledata/localcache/mustache/1675549525/iomadboost/__Mustache_378182edff0932b3ddd4d9c9caea7dfd.php: call to __Mustache_eb4b45ecbe4f60a84b8a56326203be46->renderInternal()
    line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_378182edff0932b3ddd4d9c9caea7dfd->renderInternal()
    line 204 of /lib/outputrenderers.php: call to Mustache_Template->render()
    line 113 of /theme/iomadboost/layout/drawers.php: call to renderer_base->render_from_template()
    line 1515 of /lib/outputrenderers.php: call to include()
    line 1441 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 179 of /my/index.php: call to core_renderer->header()
```

Checking further, I enabled Display debug messages (debugdisplay) in Site Admin / Development / Debugging.
Additional errors are shown in both the c1 and c2 companies along with the debug error above.

```
Notice: Undefined variable: myrecs in /var/www/vhosts/001-dev.domain.ca/iomad/blocks/mycourses/locallib.php on line 65

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/001-dev.domain.ca/iomad/blocks/mycourses/locallib.php on line 65
```

But, it also shows in the main super user company (dev.domain.ca) when viewing "My courses" or "Dashboard"
the Undefined warning is hidden by the title bar, but can be seen in the source.

line 65 was introduced in 364f566e72d0cc8c5d8811448c7e04630ae50d2c


Hope that helps!  If this is only on my installation for some reason can you point me to what might be causing it?
Thanks!

**Comment by dallenk** [comment]
defining $myrecs before the foreach clears up the undefined warning, from both sites, the main, and companies C1 and C2.  But the invalid argument remains, as does the Category error.

    $myrecs = null;

but I am not a very good coder, I'm only good at finding problems lol

**Comment by dallenk** [comment]
well.. I wrote a clunky script to quickly (but probably not efficiently) restore an IOMAD database, iomad and moodledata folders from backups that I created from another equally inefficient but functional script.

```
git log -1
commit 1bd48908c13f20641aa7cfeb44e75599d6ffc4f0 (HEAD -> IOMAD_400_STABLE, origin/IOMAD_400_STABLE)
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Mon Nov 14 11:35:39 2022 +0000

    IOMAD: 4.0.5 release

```
works - Is old, no errors but likely contains the course category bug since I can use a url to a closed shared course and enroll in it without it being shared to the company.  I'm assuming this is the issue the fix was targeted too?

### sudo -u www-data git pull origin a2702e7651d985bf33167919177b0a2886c6d2df
```
git log -1
commit a2702e7651d985bf33167919177b0a2886c6d2df (HEAD -> IOMAD_400_STABLE)
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Thu Jan 26 17:19:22 2023 +0000

    IOMAD: missing/incorrect lang strings
```
Works - no errors but likely contains the course category bug since I can use a url to a closed shared course and enroll in it without it being shared to the company

### sudo -u www-data git pull origin 9b02e412556ac91f905c08779618e2282713a570
```
git log -1
commit 9b02e412556ac91f905c08779618e2282713a570 (HEAD -> IOMAD_400_STABLE)
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Wed Feb 1 13:29:12 2023 +0000

    IOMAD: direct URL to a course category doesn't check if a user can see it or not.
```
Cannot access "my courses" or "Dashboard" 
no errors shown from Display debug messages(debugdisplay) enabled
Developer debug shows stack trace errors:
```
Error
Unknown category
Debug info:
Error code: unknowncategory
Stack trace: 
```

### git pull && git log -1
```
 git log -1
commit d0ef84f7b46bfa696ff977df2c2ca5d814836549 (HEAD -> IOMAD_400_STABLE, origin/IOMAD_400_STABLE)
Author: Derick Turner <derick@e-learndesign.co.uk>
Date:   Thu Feb 2 16:01:52 2023 +0000

    IOMAD: course catalog change caused an issue with the new 'courses' page
```
Companies fail to access "My Courses" and "Dashboard"
Main host (dev.domain.ca) shows these php warnings on "My Courses" and "Dashboard"

Notice: Undefined variable: myrecs in /var/www/vhosts/001-dev.domain.ca/iomad/blocks/mycourses/locallib.php on line 65

Warning: Invalid argument supplied for foreach() in /var/www/vhosts/001-dev.domain.ca/iomad/blocks/mycourses/locallib.php on line 65


I'm fairly certain this won't be limited to just my own installation, but I also don't see anyone else reporting it.
I'm out of ideas.

**Comment by turf212** [comment]
There was a typo that initial $recs = []; should have been for $myrecs.  I've pushed that fix.

FYI - if there haven't been any changes to version numbers you can just change the code back.  

The original issue here is that users were able to see course categories they shouldn't have so there was code added to filter out categories like that if they tried o go directly to it via ID switching on the URL.

The companies you have will have a course category each (or should by default).  Categories the company users are allowed to se are their main company category and any subcategory thereof. Where are the courses which the user can't see?  In another companies category? In a non-company category? In their own company category?

**Comment by dallenk** [comment]
that did clear up the undefined error, but other companies are still showing "Unknown category" when viewing Dashboard or "My courses"
The site admin has no problem
```
My Courses : http://c1.dev.domain.ca/my/courses.php
Dashboard: http://c1.dev.domain.ca/my/
```

That's what I figured the original issue was, as I could use the URL to the category and access courses not shared with companies.  It's not that users in companies c1 or c2 can't see courses.. they can't see anything at all except for the error.

If I go "home" using c1.dev.domain.ca/?redirect=0 Then I can click any link listed under available courses and access them.. the problem only happens when clicking the Dashboard, or My courses link.

**Comment by dallenk** [comment]
OK progress - I just discovered this will happen under conditions.  I found a user was still a participant of a course, even after being un-enrolled.  I'll restore to the most recent backup and replicate it. Perhaps showing the error but not causing the exception to be shown might help pinpoint why?

I can give you access to my dev site if that will help.  I will restore it and show you exactly how to clear it by removing enrollments that seem to be stuck.

**Comment by turf212** [comment]
that works for me.  You can send me the details directly at derick at e-learndesign.co.uk 

I'm assuming from what you said that the user who is seeing this error is enrolled on a course within that category.  So, by Moodle rules would see the category but from our security rules shouldn't.  Are these shared courses from another company / company category?

**Comment by dallenk** [comment]
So this is interesting.. on my dev site, I removed every single enrollment an all course, un-assigned all courses from all companies and the error still remained. I my previous test, I must have changed the share type in addition to removing the members and lost track of the things I tried.

When I set all courses to "self-enrollment / closed sharing" on the owner company, the error disappears.  Setting just one course (any course) to open sharing triggers that error.

```
is-licensed     / is-shared       =  result

self-enrollment /  open sharing   = error
yes             /  open sharing   = no error
no              /  open sharing   = no error
self-enrollment /  closed sharing = no error
yes             /  closed sharing = no error
no              /  closed sharing = no error
```

this makes no sense to me haha.  I will email you credentials for all three companies.. I just renamed them to make it a little clearer.

**Comment by turf212** [comment]
Found the 2 underlying issues which were causing this.

1 - was the user was enrolled onto a course that wasn't in a category the company wouldn't normally have access to (e.g. shared from another company)
2 - The user had access to a course (self enrol) that was shared from a category that a company wouldn't normally have access to.

Fixes have been pushed.

**Comment by dallenk** [comment]
fantastic, i just pulled f4e5832f9b981e9dbf4bf43195252aeed8549ce8 and the dev site appears to be working..

..I wish I knew how to do what you do...
