### ISSUE TITLE
Redirection error while creating child company

### ISSUE THREAD

**Issue by sheetal071** [iomad/iomad#1780]
Iomad version: 4.1.2
PHP version: 7.4.33
Database: mysql (8.0.32)

When we create a child company and also selects a **Parent company** in the **Advanced Company Settings** then it is created successfully but the page is redirected back to the **Create Child Company** form only.

**Comment by turf212** [comment]
Fixed by pull request

**Comment by sheetal071** [comment]
Hi turf,
I have pulled the latest code. The above error isn't fixed yet. When we create the child company the page is redirected back to the same form i.e. **Create Child Company** form.

**Comment by turf212** [comment]
Can confirm the same behaviour.  This was from the link "create child company" on the company management page.  Will check further.

**Comment by turf212** [comment]
The flow of the child company creation process has changed completely as part of #2044
