### ISSUE TITLE
Assign license via API does not work

### ISSUE THREAD

**Issue by actXc** [iomad/iomad#673]
is some one able to create a license using the xmlrpc API?
even with the newest function it does not work.
There is no example in the wsclient folder.
Any solution planned?

**Comment by turf212** [comment]
Looks like there were a couple of parameter issues with the validation.  I've fixed this and the unallocate license calls.

**Comment by actXc** [comment]
Thank you for the clarification in this function.
the **create_license** function is still not ok.
My pull request for io´mad_32_stable was accepted - but is missing in iomad_33_stable
But its still not working to assign a course to the license while the license is created.
