### ISSUE TITLE
Error in local/iomad_signup/signup.php

### ISSUE THREAD

**Issue by fesaner** [iomad/iomad#957]
I tried using the iomad_signup code and an error was generated. The code on line 32, $wanteddepartment = optiona_param('dept', '', PARAM_CLEAN); is missing an 'l' in optiona_param
 
The line should be $wanteddepartment = optional_param('dept', '', PARAM_CLEAN);

Floyd

**Comment by turf212** [comment]
This was fixed in commit 17c0ee2ef7f09ab27ec01eb4309abf7758cae955 in the 3.2 branch.  It's been fixed since Dec 17 2017 in 3.3 and later.

**Comment by fesaner** [comment]
Well, if it was fixed in Dec 17, 2017, it has come back.  The error I reported was in IOMAD_34_STABLE which I downloaded on June 14, this month.  I just downloaded the latest version from github,  IOMAD_34_STABLE, today, June 24, and the error is still there (missing l in optiona_param....)

The file is /local/iomad_signup/signup.php  and the code is
Line 32: $wanteddepartment = optiona_param('dept', '', PARAM_CLEAN);

Floyd

**Comment by jgdk** [comment]
In Iomad 3.10 the local signup page is still buggy:

Debug info:
Error code: missingparam
×Stack trace:
line 498 of /lib/setuplib.php: moodle_exception thrown
line 566 of /lib/moodlelib.php: call to print_error()
line 28 of /local/iomad_signup/signup.php: call to required_param()

Hope it can help.

Jens

**Comment by turf212** [comment]
We moved away from using that in IOMAD 3.8.  The company login/signup and so on now use the pages from Moodle core which were updated to include all of the local/signup.php code and more.  This also allowed for per company URLs and branded signout pages.

Admittedly I thought that the local/signup.php pages were forwarding for the core pages - so I'll go check this now.

**Comment by jgdk** [comment]
That's great, let me know if you need help with the testing or documentation of more of IOMAD :-)

**Comment by jgdk** [comment]
> We moved away from using that in IOMAD 3.8. The company login/signup and so on now use the pages from Moodle core which were updated to include all of the local/signup.php code and more. This also allowed for per company URLs and branded signout pages.
> 
> Admittedly I thought that the local/signup.php pages were forwarding for the core pages - so I'll go check this now.

Btw: The core signup.php also goes white with the company id and short name in the url.
